-- MySQL Script generated by MySQL Workbench
-- Fri Oct 13 02:53:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SICU
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SICU` ;

-- -----------------------------------------------------
-- Schema SICU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SICU` DEFAULT CHARACTER SET utf8 ;
USE `SICU` ;

-- -----------------------------------------------------
-- Table `SICU`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`region` ;

CREATE TABLE IF NOT EXISTS `SICU`.`region` (
  `idregion` INT NOT NULL AUTO_INCREMENT,
  `nombre_region` VARCHAR(45) NULL,
  PRIMARY KEY (`idregion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`comuna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`comuna` ;

CREATE TABLE IF NOT EXISTS `SICU`.`comuna` (
  `idcomuna` INT NOT NULL AUTO_INCREMENT,
  `nombre_comuna` VARCHAR(45) NOT NULL,
  `region_idregion` INT NOT NULL,
  PRIMARY KEY (`idcomuna`),
  INDEX `fk_comuna_region1_idx` (`region_idregion` ASC),
  CONSTRAINT `fk_comuna_region1`
    FOREIGN KEY (`region_idregion`)
    REFERENCES `SICU`.`region` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `SICU`.`Colegio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`Colegio` ;

CREATE TABLE IF NOT EXISTS `SICU`.`Colegio` (
  `idColegio` INT NOT NULL AUTO_INCREMENT,
  `nombreColegio` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `comuna_idcomuna` INT NOT NULL,
  PRIMARY KEY (`idColegio`),
  INDEX `fk_Colegio_comuna1_idx` (`comuna_idcomuna` ASC),
  CONSTRAINT `fk_Colegio_comuna1`
    FOREIGN KEY (`comuna_idcomuna`)
    REFERENCES `SICU`.`comuna` (`idcomuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`Curso` ;

CREATE TABLE IF NOT EXISTS `SICU`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nombre_curso` VARCHAR(45) NOT NULL,
  `cantidad_alumnos` INT NULL,
  `Colegio_idColegio` INT NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `fk_Curso_Colegio_idx` (`Colegio_idColegio` ASC),
  CONSTRAINT `fk_Curso_Colegio`
    FOREIGN KEY (`Colegio_idColegio`)
    REFERENCES `SICU`.`Colegio` (`idColegio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`marca` ;

CREATE TABLE IF NOT EXISTS `SICU`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(45) NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`categoria` ;

CREATE TABLE IF NOT EXISTS `SICU`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`Producto` ;

CREATE TABLE IF NOT EXISTS `SICU`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NULL,
  `ubicacion_mayorista` VARCHAR(45) NULL,
  `ubicacion_minorista` VARCHAR(45) NULL,
  `precio_mayorista` INT NULL,
  `precio_minorista` INT NULL,
  `precio_venta` INT NULL,
  `foto` VARCHAR(255) NULL,
  `marca_idmarca` INT NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_marca1_idx` (`marca_idmarca` ASC),
  INDEX `fk_Producto_categoria1_idx` (`categoria_idcategoria` ASC),
  CONSTRAINT `fk_Producto_marca1`
    FOREIGN KEY (`marca_idmarca`)
    REFERENCES `SICU`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `SICU`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`cliente` ;

CREATE TABLE IF NOT EXISTS `SICU`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `rut_cliente` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `comuna_idcomuna` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_comuna1_idx` (`comuna_idcomuna` ASC),
  CONSTRAINT `fk_cliente_comuna1`
    FOREIGN KEY (`comuna_idcomuna`)
    REFERENCES `SICU`.`comuna` (`idcomuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`medio_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`medio_pago` ;

CREATE TABLE IF NOT EXISTS `SICU`.`medio_pago` (
  `idmedio_pago` INT NOT NULL AUTO_INCREMENT,
  `nombre_medio_pago` VARCHAR(45) NULL,
  `porcentaje_comision` DECIMAL(2) NULL,
  PRIMARY KEY (`idmedio_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`L1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`L1` ;

CREATE TABLE IF NOT EXISTS `SICU`.`L1` (
  `idL1` INT NOT NULL AUTO_INCREMENT,
  `nombre_l1` VARCHAR(45) NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idL1`),
  INDEX `fk_L1_Curso1_idx` (`Curso_idCurso` ASC),
  CONSTRAINT `fk_L1_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `SICU`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`L1_Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`L1_Productos` ;

CREATE TABLE IF NOT EXISTS `SICU`.`L1_Productos` (
  `idL1_Productos` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `comentario` VARCHAR(140) NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idL1_Productos`),
  INDEX `fk_L1_Productos_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_L1_Productos_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `SICU`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`L2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`L2` ;

CREATE TABLE IF NOT EXISTS `SICU`.`L2` (
  `idL2` INT NOT NULL AUTO_INCREMENT,
  `L1_idL1` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idL2`),
  INDEX `fk_L2_L11_idx` (`L1_idL1` ASC),
  INDEX `fk_L2_cliente1_idx` (`cliente_idcliente` ASC),
  CONSTRAINT `fk_L2_L11`
    FOREIGN KEY (`L1_idL1`)
    REFERENCES `SICU`.`L1` (`idL1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_L2_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `SICU`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`estado` ;

CREATE TABLE IF NOT EXISTS `SICU`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`L2_Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`L2_Productos` ;

CREATE TABLE IF NOT EXISTS `SICU`.`L2_Productos` (
  `idL2_Productos` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `Producto_idProducto` INT NOT NULL,
  `estado_idestado` INT NOT NULL,
  PRIMARY KEY (`idL2_Productos`, `Producto_idProducto`, `estado_idestado`),
  INDEX `fk_L2_Productos_Producto1_idx` (`Producto_idProducto` ASC),
  INDEX `fk_L2_Productos_estado1_idx` (`estado_idestado` ASC),
  CONSTRAINT `fk_L2_Productos_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `SICU`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_L2_Productos_estado1`
    FOREIGN KEY (`estado_idestado`)
    REFERENCES `SICU`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICU`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SICU`.`pedido` ;

CREATE TABLE IF NOT EXISTS `SICU`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `precio_total` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `estado_idestado` INT NOT NULL,
  `medio_pago_idmedio_pago` INT NOT NULL,
  `comuna_idcomuna` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `estado_idestado`, `medio_pago_idmedio_pago`, `comuna_idcomuna`, `cliente_idcliente`),
  INDEX `fk_pedido_estado1_idx` (`estado_idestado` ASC),
  INDEX `fk_pedido_medio_pago1_idx` (`medio_pago_idmedio_pago` ASC),
  INDEX `fk_pedido_comuna1_idx` (`comuna_idcomuna` ASC),
  INDEX `fk_pedido_cliente1_idx` (`cliente_idcliente` ASC),
  CONSTRAINT `fk_pedido_estado1`
    FOREIGN KEY (`estado_idestado`)
    REFERENCES `SICU`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_medio_pago1`
    FOREIGN KEY (`medio_pago_idmedio_pago`)
    REFERENCES `SICU`.`medio_pago` (`idmedio_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_comuna1`
    FOREIGN KEY (`comuna_idcomuna`)
    REFERENCES `SICU`.`comuna` (`idcomuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `SICU`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
